# Generated manually for the software_store app.

import django.db.models.deletion
import software_store.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200
                    )
                ),
                (
                    'slug',
                    models.SlugField(
                        unique=True
                    )
                ),
                (
                    'description',
                    models.TextField()
                ),
                (
                    'version',
                    models.CharField(
                        max_length=50
                    )
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10
                    )
                ),
                (
                    'proton_drive_link',
                    models.URLField(
                        blank=True,
                        max_length=1000
                    )
                ),
                (
                    'release_notes',
                    models.TextField(
                        blank=True
                    )
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True
                    )
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True
                    )
                ),
            ],
            options={
                'ordering': (
                    'name',
                ),
            },
        ),
        migrations.CreateModel(
            name='SoftwareOrder',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'customer_name',
                    models.CharField(
                        max_length=200
                    )
                ),
                (
                    'customer_phone',
                    models.CharField(
                        max_length=50
                    )
                ),
                (
                    'customer_email',
                    models.EmailField(
                        max_length=254
                    )
                ),
                (
                    'business_name',
                    models.CharField(
                        blank=True,
                        max_length=200
                    )
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10
                    )
                ),
                (
                    'payment_method',
                    models.CharField(
                        max_length=100
                    )
                ),
                (
                    'payment_reference',
                    models.CharField(
                        blank=True,
                        max_length=200
                    )
                ),
                (
                    'payment_status',
                    models.CharField(
                        choices=[
                            (
                                'Pending',
                                'Pending'
                            ),
                            (
                                'Paid',
                                'Paid'
                            ),
                            (
                                'Rejected',
                                'Rejected'
                            ),
                        ],
                        default='Pending',
                        max_length=20
                    )
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True
                    )
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='orders',
                        to='software_store.softwareproduct'
                    )
                ),
            ],
            options={
                'ordering': (
                    '-created_at',
                ),
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'license_key',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True
                    )
                ),
                (
                    'customer_name',
                    models.CharField(
                        max_length=200
                    )
                ),
                (
                    'customer_email',
                    models.EmailField(
                        max_length=254
                    )
                ),
                (
                    'allowed_devices',
                    models.PositiveIntegerField(
                        default=1
                    )
                ),
                (
                    'expiry_date',
                    models.DateField(
                        default=software_store.models.default_license_expiry_date
                    )
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True
                    )
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='licenses',
                        to='software_store.softwareorder'
                    )
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='licenses',
                        to='software_store.softwareproduct'
                    )
                ),
            ],
            options={
                'ordering': (
                    '-created_at',
                ),
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'device_id',
                    models.CharField(
                        max_length=255
                    )
                ),
                (
                    'activated_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
                (
                    'license',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='activations',
                        to='software_store.softwarelicense'
                    )
                ),
            ],
            options={
                'ordering': (
                    '-activated_at',
                ),
            },
        ),
        migrations.CreateModel(
            name='SoftwareDownloadLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'customer_email',
                    models.EmailField(
                        max_length=254
                    )
                ),
                (
                    'ip_address',
                    models.GenericIPAddressField(
                        blank=True,
                        null=True
                    )
                ),
                (
                    'downloaded_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='download_logs',
                        to='software_store.softwareorder'
                    )
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='download_logs',
                        to='software_store.softwareproduct'
                    )
                ),
            ],
            options={
                'ordering': (
                    '-downloaded_at',
                ),
            },
        ),
        migrations.AddConstraint(
            model_name='softwarelicense',
            constraint=models.UniqueConstraint(
                fields=(
                    'order',
                ),
                name='unique_license_per_order'
            ),
        ),
        migrations.AddConstraint(
            model_name='licenseactivation',
            constraint=models.UniqueConstraint(
                fields=(
                    'license',
                    'device_id',
                ),
                name='unique_activation_per_license_device'
            ),
        ),
    ]
