# Generated by Django 6.0.5 on 2026-07-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseactivation',
            name='device_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='licenseactivation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licenseactivation',
            name='os_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='licenseactivation',
            name='windows_user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
