# Generated by Django 6.0.5 on 2026-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_store', '0002_licenseactivation_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproduct',
            name='proton_drive_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
