# Generated by Django 6.0.5 on 2026-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_store', '0003_softwareproduct_proton_drive_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_business_number', models.CharField(blank=True, max_length=100)),
                ('mpesa_account_name', models.CharField(blank=True, max_length=200)),
                ('airtel_money_number', models.CharField(blank=True, max_length=100)),
                ('airtel_money_name', models.CharField(blank=True, max_length=200)),
                ('mixx_number', models.CharField(blank=True, max_length=100)),
                ('mixx_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
