# Generated by Django 6.0.5 on 2026-07-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_store', '0004_paymentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareorder',
            name='license_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
