# Generated by Django 6.0.5 on 2026-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_store', '0005_softwareorder_license_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproduct',
            name='youtube_activation_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='youtube_installation_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='softwareproduct',
            name='youtube_overview_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
