# Generated manually for product details page content.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'software_store',
            '0007_softwareproduct_delivery_type'
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproduct',
            name='key_features',
            field=models.TextField(
                blank=True,
                help_text='Optional fallback features, one per line. Use product feature rows for richer entries.'
            ),
        ),
        migrations.CreateModel(
            name='SoftwareProductFAQ',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'question',
                    models.CharField(
                        max_length=255
                    )
                ),
                (
                    'answer',
                    models.TextField()
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(
                        default=0
                    )
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='faqs',
                        to='software_store.softwareproduct'
                    )
                ),
            ],
            options={
                'ordering': (
                    'sort_order',
                    'question',
                ),
            },
        ),
        migrations.CreateModel(
            name='SoftwareProductFeature',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'title',
                    models.CharField(
                        max_length=200
                    )
                ),
                (
                    'description',
                    models.TextField(
                        blank=True
                    )
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(
                        default=0
                    )
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='features',
                        to='software_store.softwareproduct'
                    )
                ),
            ],
            options={
                'ordering': (
                    'sort_order',
                    'title',
                ),
            },
        ),
        migrations.CreateModel(
            name='SoftwareProductScreenshot',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to='software/screenshots/'
                    )
                ),
                (
                    'caption',
                    models.CharField(
                        blank=True,
                        max_length=200
                    )
                ),
                (
                    'sort_order',
                    models.PositiveIntegerField(
                        default=0
                    )
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='screenshots',
                        to='software_store.softwareproduct'
                    )
                ),
            ],
            options={
                'ordering': (
                    'sort_order',
                    'id',
                ),
            },
        ),
    ]
