# Generated by Django 6.0.5 on 2026-07-30 09:50

import django.core.validators
import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_quiz_question_choice_quizattempt_studentanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240)),
                ('instructions', models.TextField()),
                ('maximum_score', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('passing_score', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('allow_resubmission', models.BooleanField(default=True)),
                ('maximum_attempts', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('allowed_file_extensions', models.CharField(default='pdf,doc,docx,txt,zip,py,ipynb,csv,xlsx,ppt,pptx,jpg,jpeg,png', help_text='Separate extensions using commas.', max_length=255)),
                ('maximum_file_size_mb', models.PositiveIntegerField(default=10)),
                ('require_text_submission', models.BooleanField(default=True)),
                ('require_file_submission', models.BooleanField(default=False)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='learning.lesson')),
            ],
            options={
                'ordering': ('lesson__module__course__title', 'lesson__module__order', 'lesson__order'),
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('submission_text', models.TextField(blank=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to=learning.models.assignment_submission_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Graded', 'Graded'), ('Returned for Revision', 'Returned for Revision'), ('Withdrawn', 'Withdrawn')], default='Draft', max_length=40)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_late', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('instructor_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('revision_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.assignment')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_submissions', to='learning.enrolment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignment_submissions', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_assignment_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['slug'], name='learning_as_slug_8df6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['is_published'], name='learning_as_is_publ_7751a1_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='learning_as_due_dat_9305cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('lesson', 'slug'), name='unique_assignment_slug_per_lesson'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'student', 'status'], name='learning_su_assign_1a2e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['enrolment', 'submitted_at'], name='learning_su_enrolme_14a507_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status', 'graded_at'], name='learning_su_status_47f75a_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student', 'attempt_number'), name='unique_assignment_attempt_per_student'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Draft')), fields=('assignment', 'student'), name='unique_draft_assignment_submission'),
        ),
    ]
