# Generated by Django 6.0.5 on 2026-07-30 10:46

import django.db.models.deletion
import django.utils.timezone
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_assignment_assignmentsubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('mpesa_business_number', models.CharField(blank=True, max_length=100)),
                ('mpesa_account_name', models.CharField(blank=True, max_length=200)),
                ('airtel_business_number', models.CharField(blank=True, max_length=100)),
                ('airtel_account_name', models.CharField(blank=True, max_length=200)),
                ('mixx_business_number', models.CharField(blank=True, max_length=100)),
                ('mixx_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=200)),
                ('card_instructions', models.TextField(blank=True)),
                ('general_payment_instructions', models.TextField(blank=True)),
                ('require_proof_for_mobile_money', models.BooleanField(default=True)),
                ('require_proof_for_bank_transfer', models.BooleanField(default=True)),
                ('payment_support_email', models.EmailField(blank=True, max_length=254)),
                ('payment_support_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Learning payment settings',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_learning_payment_settings')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('payment_method', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money'), ('Mixx by Yas', 'Mixx by Yas'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card'), ('Other', 'Other')], max_length=40)),
                ('transaction_reference', models.CharField(max_length=120)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to=learning.models.payment_proof_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('proof_file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('student_notes', models.TextField(blank=True)),
                ('administrator_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_payments', to='learning.course')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='learning.enrolment')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunded_learning_payments', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_learning_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_learning_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
                'permissions': (('verify_learning_payment', 'Can verify learning payment'), ('reject_learning_payment', 'Can reject learning payment'), ('refund_learning_payment', 'Can refund learning payment'), ('view_all_learning_payments', 'Can view all learning payments')),
                'indexes': [models.Index(fields=['student', 'status'], name='learning_pa_student_7ab4f0_idx'), models.Index(fields=['course', 'status'], name='learning_pa_course_612e8c_idx'), models.Index(fields=['enrolment', 'status'], name='learning_pa_enrolm_2f7614_idx'), models.Index(fields=['transaction_reference'], name='learning_pa_transa_4bd0b5_idx'), models.Index(fields=['submitted_at'], name='learning_pa_submitt_2403e6_idx'), models.Index(fields=['verified_at'], name='learning_pa_verifie_b25777_idx'), models.Index(fields=['payment_method', 'status'], name='learning_pa_payment_ad4f6d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Pending')), fields=('enrolment',), name='unique_pending_learning_payment_per_enrolment'), models.UniqueConstraint(condition=models.Q(('status', 'Paid')), fields=('enrolment',), name='unique_paid_learning_payment_per_enrolment'), models.UniqueConstraint(condition=models.Q(('transaction_reference', ''), _negated=True), fields=('transaction_reference',), name='unique_learning_payment_reference')],
            },
        ),
    ]
