# Generated by Django 6.0.5 on 2026-07-30 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_learningpaymentsettings_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Enrolment', 'Enrolment'), ('Payment', 'Payment'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Review', 'Review'), ('Announcement', 'Announcement'), ('Course Completion', 'Course Completion'), ('Certificate', 'Certificate'), ('System', 'System')], default='System', max_length=40),
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Hidden', 'Hidden')], default='Pending', max_length=30)),
                ('is_approved', models.BooleanField(default=False)),
                ('moderation_notes', models.TextField(blank=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.course')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_reviews', to='learning.enrolment')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_course_reviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': (('moderate_course_reviews', 'Can moderate course reviews'), ('approve_course_review', 'Can approve course review'), ('reject_course_review', 'Can reject course review'), ('hide_course_review', 'Can hide course review'), ('view_all_course_reviews', 'Can view all course reviews')),
                'indexes': [models.Index(fields=['course', 'status'], name='learning_re_course_21dc8c_idx'), models.Index(fields=['student', 'created_at'], name='learning_re_student_7bf2e7_idx'), models.Index(fields=['status', 'created_at'], name='learning_re_status_6682c6_idx'), models.Index(fields=['rating'], name='learning_re_rating_c80d28_idx'), models.Index(fields=['moderated_at'], name='learning_re_moderat_2363f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_course_review_per_student'), models.UniqueConstraint(fields=('enrolment',), name='unique_course_review_per_enrolment'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='course_review_rating_between_1_and_5'), models.CheckConstraint(condition=models.Q(models.Q(('is_approved', True), ('status', 'Approved')), models.Q(('is_approved', False), ('status__in', ['Pending', 'Rejected', 'Hidden'])), _connector='OR'), name='course_review_approval_consistent')],
            },
        ),
    ]
