# Generated by Codex on 2026-07-31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_notification_notification_type_coursereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=80, unique=True)),
                ('verification_code', models.CharField(max_length=120, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='learning/certificates/')),
                ('is_valid', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='learning.course')),
                ('enrolment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='learning.enrolment')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_learning_certificates', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_learning_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_certificates', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-issued_at',),
                'permissions': (('view_all_certificates', 'Can view all learning certificates'), ('revoke_certificate', 'Can revoke learning certificate'), ('restore_certificate', 'Can restore learning certificate'), ('regenerate_certificate', 'Can regenerate learning certificate PDF'), ('view_course_certificates', 'Can view course certificates')),
                'indexes': [models.Index(fields=['student', 'issued_at'], name='learning_ce_student_4b4964_idx'), models.Index(fields=['course', 'issued_at'], name='learning_ce_course_91f7d8_idx'), models.Index(fields=['is_valid', 'issued_at'], name='learning_ce_is_vali_ea0667_idx'), models.Index(fields=['verification_code'], name='learning_ce_verific_b1899d_idx')],
            },
        ),
    ]
