# Generated by Codex on 2026-08-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_payment_audit_logs(apps, schema_editor):

    Payment = apps.get_model('learning', 'Payment')
    PaymentAuditLog = apps.get_model('learning', 'PaymentAuditLog')

    logs = []

    for payment in Payment.objects.all().iterator():
        logs.append(
            PaymentAuditLog(
                payment_id=payment.pk,
                action='Submitted',
                previous_status='',
                new_status=payment.status,
                note='Initial audit record created for an existing payment.',
            )
        )

    PaymentAuditLog.objects.bulk_create(logs, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0008_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Submitted', 'Submitted'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded'), ('Updated', 'Updated')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_payment_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='learning.payment')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(fields=['payment', 'created_at'], name='learning_pa_audit_pay_6e0a_idx'),
                    models.Index(fields=['action'], name='learning_pa_audit_act_225f_idx'),
                ],
            },
        ),
        migrations.RunPython(
            backfill_payment_audit_logs,
            migrations.RunPython.noop
        ),
    ]
