# Generated by Codex on 2026-08-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_certificate_approval(apps, schema_editor):

    Certificate = apps.get_model('learning', 'Certificate')

    for certificate in Certificate.objects.all().iterator():
        if certificate.is_valid:
            certificate.approval_status = 'Approved'
            certificate.approved_at = certificate.issued_at
        else:
            certificate.approval_status = 'Revoked'
        certificate.save(
            update_fields=[
                'approval_status',
                'approved_at',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0009_paymentauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='approval_status',
            field=models.CharField(
                choices=[
                    ('Pending Approval', 'Pending Approval'),
                    ('Approved', 'Approved'),
                    ('Revoked', 'Revoked'),
                ],
                default='Pending Approval',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_learning_certificates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={
                'ordering': ('-issued_at',),
                'permissions': (
                    ('view_all_certificates', 'Can view all learning certificates'),
                    ('approve_certificate', 'Can approve learning certificate'),
                    ('revoke_certificate', 'Can revoke learning certificate'),
                    ('restore_certificate', 'Can restore learning certificate'),
                    ('regenerate_certificate', 'Can regenerate learning certificate PDF'),
                    ('view_course_certificates', 'Can view course certificates'),
                ),
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(
                fields=['approval_status', 'issued_at'],
                name='learning_ce_approv_1f41_idx',
            ),
        ),
        migrations.RunPython(
            backfill_certificate_approval,
            migrations.RunPython.noop,
        ),
    ]
